Update links to Hunter documentation
ethereum-mining/ethminer pull request #2186
Opened 2021-02-22 21:36 UTC by executionByFork

https://docs.hunter.sh is no longer a valid URL. The document files for hunter seem to be hosted at https://hunter.readthedocs.io now.

2021-02-27 22:33 UTC, themar7777 approved these changes

2021-02-27 22:36 UTC, themar7777 commented on docs/BUILD.md
> -[`-DHUNTER_ENABLED=OFF`](https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-enabled)
Two

2021-02-27 22:38 UTC, themar7777 requested changes

2021-02-27 22:38 UTC, themar7777 commented on docs/BUILD.md
>  ## Disable Hunter
Duplicate of #

2021-03-07 15:59 UTC, hamedtayeban22 commented
#2186

2021-03-07 16:01 UTC, hamedtayeban22 commented
@hamedtayeban22

2022-08-08 15:51 UTC, closed without merging